version: '3'

services:
  drf:
    build:
      context: ./
      dockerfile: ./docker/Dockerfile
    env_file:
      - .env
    ports:
      - 8000:8000
    volumes:
      - ./:/drf-tutorial/
#    entrypoint: /entrypoint/cerebro.sh
#    command: python3 manage.py runserver 0.0.0.0:8000
    tty: true
    stdin_open: true

